#!/bin/bash
# vim: set ft=sh

set -e

OUTPUT="$PWD/bosh-rc"
VERSION="$(cat version/version)"

pushd admin-ui-boshrelease/

  # work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
  # into release dir, which is invalid cross-device link
  export HOME=$PWD
  gem install bosh_cli
  bosh -n create release --with-tarball --name admin-ui --version "$VERSION"
  mv dev_releases/admin-ui/admin-ui-*.tgz "$OUTPUT"
popd
