resources:
- name: admin-ui-boshrelease
  type: git
  source:
    uri: https://github.com/nimbus-cloud/admin-ui-boshrelease
    branch: concourse-ci

- name: version
  type: semver
  initial_version: 10.0.0
  source:
    bucket: {{s3_bucket}}
    key: admin-ui/current-version
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_host}}
    disable_ssl: true
#    use_v2_signing: true

- name: bosh-rc
  type: s3
  source:
    bucket: {{s3_bucket}}
    regexp: admin-ui/admin-ui-(.*).tgz
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_host}}
    disable_ssl: true
#    use_v2_signing: true

jobs:
- name: bosh-rc
  public: true
  plan:
  - get: admin-ui-boshrelease
    trigger: true
  - get: version
    params: {bump: patch}
  - task: create-bosh-rc
    file: admin-ui-boshrelease/ci/create-bosh-rc.yml
  - aggregate:
    - put: version
      params: {file: version/version}
    - put: bosh-rc
      params: {file: bosh-rc/admin-ui-*.tgz}
